data=get_data() 
a=Models('DoubleCrossOver', 'Simples')
a.strategy(SMA1=5,SMA2=20) 
a.stats()
a.graph()

data=get_data() 
b=Models('DoubleCrossOver', 'Simples') 
b.strategy(SMA1=10,SMA2=50) 
b.stats()
b.graph()

data=get_data() 
c=Models('TripleCrossOver', 'Simples')
c.strategy(SMA1=4,SMA2=9, SMA3=18) 
c.stats()
c.graph()

data=get_data() 
d=Models('TripleCrossOver', 'Simples') 
d.strategy(SMA1=2,SMA2=3, SMA3=18) 
d.stats()
d.graph()

data=get_data() 
e=Models('SingleAverage', 'Simples') 
e.strategy(SMA1=10)
e.stats()
e.graph()

data=get_data() 
f=Models('SingleAverage', 'Exponencial') 
f.strategy(SMA1=10)
f.stats()
f.graph()

data=get_data() 
g=Models('SingleAverage', 'Linear') 
g.strategy(SMA1=10)
g.stats()
g.graph()

data=get_data() 
h=Models('TripleCrossOver', 'Exponencial') 
h.strategy(SMA1=2,SMA2=3, SMA3=18) 
h.stats()
h.graph()